CREATE TABLE IF NOT EXISTS telemetry_signal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_type VARCHAR(16) NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content_type VARCHAR(128),
    content_encoding VARCHAR(32),
    resource_attributes CLOB,
    raw_json CLOB NOT NULL,
    raw_payload BLOB NOT NULL,
    item_count INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS agent_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(512) NOT NULL UNIQUE,
    agent_name VARCHAR(512),
    agent_type VARCHAR(64),
    requested_model VARCHAR(512),
    response_model VARCHAR(512),
    repository VARCHAR(2048),
    branch_name VARCHAR(1024),
    commit_sha VARCHAR(256),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_creation_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    turn_count INT NOT NULL DEFAULT 0,
    tool_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    content_captured BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS span_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT NOT NULL,
    session_id BIGINT,
    trace_id VARCHAR(64) NOT NULL,
    span_id VARCHAR(32) NOT NULL,
    parent_span_id VARCHAR(32),
    span_name VARCHAR(2048) NOT NULL,
    operation_name VARCHAR(256),
    span_kind VARCHAR(64),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    duration_ms DOUBLE PRECISION,
    status_code VARCHAR(32),
    status_message CLOB,
    model VARCHAR(512),
    agent_name VARCHAR(512),
    conversation_id VARCHAR(512),
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_creation_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    ttft_ms DOUBLE PRECISION,
    attributes_json CLOB NOT NULL,
    events_json CLOB NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES telemetry_signal(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES agent_session(id) ON DELETE CASCADE,
    UNIQUE(trace_id, span_id)
);

CREATE TABLE IF NOT EXISTS message_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    span_id BIGINT NOT NULL,
    direction VARCHAR(16) NOT NULL,
    sequence_no INT NOT NULL,
    role_name VARCHAR(64),
    content CLOB NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    FOREIGN KEY (span_id) REFERENCES span_record(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metric_or_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT NOT NULL,
    signal_type VARCHAR(16) NOT NULL,
    name VARCHAR(1024),
    occurred_at TIMESTAMP WITH TIME ZONE,
    body_json CLOB NOT NULL,
    attributes_json CLOB NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES telemetry_signal(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tool_classification_result (
    session_id BIGINT NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    version VARCHAR(64) NOT NULL,
    model VARCHAR(512) NOT NULL,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    result_json CLOB NOT NULL,
    PRIMARY KEY (session_id, request_hash),
    FOREIGN KEY (session_id) REFERENCES agent_session(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS optimization_advice_preview (
    id VARCHAR(36) PRIMARY KEY,
    session_id BIGINT NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    data_fingerprint VARCHAR(64) NOT NULL,
    prepared_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    preview_json CLOB NOT NULL,
    FOREIGN KEY (session_id) REFERENCES agent_session(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS optimization_advice_result (
    session_id BIGINT NOT NULL,
    advice_hash VARCHAR(64) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    data_fingerprint VARCHAR(64) NOT NULL,
    version VARCHAR(64) NOT NULL,
    catalog_version VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    model VARCHAR(512) NOT NULL,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    result_json CLOB NOT NULL,
    PRIMARY KEY (session_id, advice_hash),
    FOREIGN KEY (session_id) REFERENCES agent_session(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS round_discussion (
    id VARCHAR(36) PRIMARY KEY,
    session_id BIGINT NOT NULL,
    version VARCHAR(64) NOT NULL,
    model VARCHAR(512) NOT NULL,
    evidence_hash VARCHAR(64) NOT NULL,
    snapshot_json CLOB NOT NULL,
    copilot_session_id VARCHAR(512),
    revision INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (session_id) REFERENCES agent_session(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS round_discussion_turn (
    id VARCHAR(36) PRIMARY KEY,
    discussion_id VARCHAR(36) NOT NULL,
    client_request_id VARCHAR(36) NOT NULL,
    question CLOB NOT NULL,
    status VARCHAR(32) NOT NULL,
    answer_json CLOB,
    error_message CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (discussion_id) REFERENCES round_discussion(id) ON DELETE CASCADE,
    UNIQUE(discussion_id, client_request_id)
);

CREATE INDEX IF NOT EXISTS idx_signal_received ON telemetry_signal(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_last_seen ON agent_session(last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_span_session ON span_record(session_id, started_at);
CREATE INDEX IF NOT EXISTS idx_span_trace ON span_record(trace_id, started_at);
CREATE INDEX IF NOT EXISTS idx_message_span ON message_record(span_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_classification_session ON tool_classification_result(session_id, analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_advice_preview_session ON optimization_advice_preview(session_id, prepared_at DESC);
CREATE INDEX IF NOT EXISTS idx_advice_preview_expiry ON optimization_advice_preview(expires_at);
CREATE INDEX IF NOT EXISTS idx_advice_result_session ON optimization_advice_result(session_id, analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_round_discussion_session ON round_discussion(session_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_round_discussion_turns ON round_discussion_turn(discussion_id, created_at);
